#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::IODUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{dump_iod} = {
    v => 1.1,
    summary => 'Parse IOD using Config::IOD::Reader and display the result',
    args => {
        %App::IODUtils::common_args,
    },
    result_naked => 1,
    'cmdline.default_format' => 'json-pretty',
};
sub dump_iod {
    my %args = @_;

    my $reader = App::IODUtils::_get_reader(\%args);

    $reader->read_string($args{iod});
}

my $cli = Perinci::CmdLine::Any->new(
    url => '/main/dump_iod',
    pass_cmdline_object => 1,
    read_config => 0,
    read_env => 0,
);

# so help message can be more helpful
$cli->{common_opts}{format}{default} = 'json-pretty';
$cli->{common_opts}{naked_res}{default} = 1;

$cli->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % dump-iod /path/to/file.iod
