#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::IODUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{get_iod_key} = {
    v => 1.1,
    summary => 'Get key value from IOD configration file',
    args => {
        %App::IODUtils::common_args,
        section => {
            schema  => 'str*',
            req     => 1,
            pos     => 1,
        },
        key => {
            schema  => 'str*',
            req     => 1,
            pos     => 2,
        },
    },
};
sub get_iod_key {
    my %args = @_;

    my $reader = App::IODUtils::_get_reader(\%args);

    my $hoh = $reader->read_string($args{iod});

    my $section = $args{section};
    my $key     = $args{key};

    return [404, "No such section"] unless exists $hoh->{$section};
    return [404, "No such key"] unless exists $hoh->{$section}{$key};

    [200, "OK", $hoh->{$section}{$key}];
}

Perinci::CmdLine::Any->new(
    url => '/main/get_iod_key',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % get-iod-key /path/to/file.iod section key
