#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::IODUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{list_iod_sections} = {
    v => 1.1,
    summary => 'List all sections of an IOD configuration file',
    args => {
        %App::IODUtils::common_args,
    },
};
sub list_iod_sections {
    my %args = @_;

    my $reader = App::IODUtils::_get_reader(\%args);

    my $hoh = $reader->read_string($args{iod});
    [200, "OK", [sort keys %$hoh]];
}

Perinci::CmdLine::Any->new(
    url => '/main/list_iod_sections',
    read_config => 0,
    read_env => 0,
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % list-iod-sections /path/to/file.iod
