#!perl

# DATE
# VERSION

use 5.010;
use strict;
use warnings;

use App::IODUtils;
use Perinci::CmdLine::Any;

our %SPEC;
$SPEC{parse_iod} = {
    v => 1.1,
    summary => 'Parse IOD using Config::IOD module and show the raw result',
    description => <<'_',

Mostly only useful for developer for debugging purposes.

_
    args => {
        %App::IODUtils::common_args,
    },
    result_naked => 1,
    'cmdline.default_format' => 'json-pretty',
};
sub parse_iod {
    my %args = @_;

    my $parser = App::IODUtils::_get_parser(\%args);

    $parser->read_string($args{iod})->{_parsed};
}

my $cli = Perinci::CmdLine::Any->new(
    url => '/main/parse_iod',
    pass_cmdline_object => 1,
    read_config => 0,
    read_env => 0,
);

# so help message can be more helpful
$cli->common_opts->{format}{default} = 'json-pretty';
$cli->common_opts->{naked_res}{default} = 1;

$cli->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

Basic usage:

 % parse-iod /path/to/file.iod
